# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 191f11813c5924345dfd1b69a8135354782e45d4448447f1262f3adf04de4f036d223d84b1875e3e30e5b7a185c1737feae50a911fbadd8255a25c679f669592

test:
  secret_key_base: 9a53b389023b79a97cc25332d618d54fb8093e1031f0aea9400dfac1ca99646b626613992f144c35d68ee365ba7c235c8abcf435e068aa2390166dd11a109bc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
